
import type { Book, User, Transaction } from '@/types';

export const mockUsers: User[] = [
  { id: 'user1', email: 'student1@pes.edu', role: 'user', name: 'Aisha Sharma' },
  { id: 'user2', email: 'student2@pes.edu', role: 'user', name: 'Rohan Verma'},
  { id: 'user3', email: 'faculty1@pes.edu', role: 'user', name: 'Dr. Priya Singh' },
  { id: 'admin1', email: 'admin@pes.edu', role: 'admin', name: 'Library Admin PES' },
];

const today = new Date();
const addDays = (date: Date, days: number) => {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
};

export const mockBooks: Book[] = [
  {
    id: 'book1',
    title: 'The Digital Fortress',
    author: 'Dan Brown',
    isbn: '978-0307277040',
    status: 'issued',
    category: 'Thriller',
    publishedDate: '1998',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'book cover',
    issueDetails: {
      userId: 'user1',
      userName: 'Aisha Sharma',
      issueDate: addDays(today, -10).toISOString(),
      dueDate: addDays(today, 4).toISOString(),
    },
    description: 'A gripping thriller about cryptography and national security.'
  },
  {
    id: 'book2',
    title: 'Artificial Intelligence: A Modern Approach',
    author: 'Stuart Russell & Peter Norvig',
    isbn: '978-0134610993',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2020',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'textbook cover',
    description: 'The leading textbook in Artificial Intelligence.'
  },
  {
    id: 'book3',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    isbn: '978-0062316097',
    status: 'available',
    category: 'History',
    publishedDate: '2015',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'history book',
    description: 'A groundbreaking narrative of humanity\'s creation and evolution.'
  },
  {
    id: 'book4',
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    isbn: '978-0132350884',
    status: 'donated_pending_approval',
    category: 'Computer Science',
    publishedDate: '2008',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'coding book',
    donatedBy: { userId: 'user2', userName: 'Rohan Verma', date: addDays(today, -2).toISOString() },
    description: 'Essential reading for any software developer.'
  },
  {
    id: 'book5',
    title: 'The Laws of Thermodynamics',
    author: 'Peter Atkins',
    isbn: '978-0199572199',
    status: 'issued',
    category: 'Physics',
    publishedDate: '2010',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'science textbook',
    issueDetails: {
      userId: 'user3',
      userName: 'Dr. Priya Singh',
      issueDate: addDays(today, -20).toISOString(),
      dueDate: addDays(today, -5).toISOString(), // Overdue
    },
    description: 'A concise introduction to the principles of thermodynamics.'
  },
  {
    id: 'book6',
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    isbn: '978-0262033848',
    status: 'donated_approved',
    category: 'Computer Science',
    publishedDate: '2009',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'algorithms textbook',
    donatedBy: { userId: 'user1', userName: 'Aisha Sharma', date: addDays(today, -30).toISOString() },
    description: 'A comprehensive guide to algorithms and data structures.'
  },
  {
    id: 'book7',
    title: 'Practical Electronics for Inventors',
    author: 'Paul Scherz & Simon Monk',
    isbn: '978-1259587542',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2016',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'electronics circuits',
    description: 'A hands-on guide to electronics, from basic theory to circuit design.'
  },
  {
    id: 'book8',
    title: 'The Art of Electronics',
    author: 'Paul Horowitz & Winfield Hill',
    isbn: '978-0521809269',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2015',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'electronics reference',
    description: 'A comprehensive and authoritative text on analog and digital electronics.'
  },
  {
    id: 'book9',
    title: 'Fundamentals of Microelectronics',
    author: 'Behzad Razavi',
    isbn: '978-1119523878',
    status: 'maintenance',
    category: 'Electronics',
    publishedDate: '2020',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'microelectronics textbook',
    description: 'Covers the analysis and design of electronic circuits, focusing on microelectronics.'
  },
  {
    id: 'book10',
    title: 'Digital Design and Computer Architecture',
    author: 'David Harris & Sarah Harris',
    isbn: '978-0128200622',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2021',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'digital design',
    description: 'Takes the reader from the fundamentals of digital logic to the actual design of a MIPS processor.'
  },
  // Start of existing electronics books (issued)
  {
    id: 'elec001',
    title: 'Grob\'s Basic Electronics',
    author: 'Mitchel E. Schultz',
    isbn: '978-0073373874',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2015',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'electronics textbook',
    issueDetails: {
      userId: 'user1',
      userName: 'Aisha Sharma',
      issueDate: addDays(today, -12).toISOString(),
      dueDate: addDays(today, 2).toISOString(), // Due soon
    },
    description: 'A foundational text covering DC/AC circuits, semiconductors, and basic electronic devices.'
  },
  {
    id: 'elec002',
    title: 'Electronic Devices and Circuit Theory',
    author: 'Robert L. Boylestad & Louis Nashelsky',
    isbn: '978-0132622264',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2012',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'circuit theory',
    issueDetails: {
      userId: 'user2',
      userName: 'Rohan Verma',
      issueDate: addDays(today, -5).toISOString(),
      dueDate: addDays(today, 9).toISOString(),
    },
    description: 'Comprehensive coverage of electronic devices and circuits with a focus on analysis and design.'
  },
  {
    id: 'elec003',
    title: 'Principles of Electric Circuits',
    author: 'Thomas L. Floyd & David M. Buchla',
    isbn: '978-0134879413',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2019',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'electric circuits',
    issueDetails: {
      userId: 'user1',
      userName: 'Aisha Sharma',
      issueDate: addDays(today, -25).toISOString(),
      dueDate: addDays(today, -11).toISOString(), // Overdue
    },
    description: 'A clear and straightforward presentation of the fundamentals of electric circuits.'
  },
  {
    id: 'elec004',
    title: 'Microelectronic Circuits',
    author: 'Adel S. Sedra & Kenneth C. Smith',
    isbn: '978-0190853464',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2019',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'microchip circuit',
    issueDetails: {
      userId: 'user2',
      userName: 'Rohan Verma',
      issueDate: addDays(today, -8).toISOString(),
      dueDate: addDays(today, 6).toISOString(),
    },
    description: 'A classic text known for its comprehensive treatment of microelectronic circuits.'
  },
  {
    id: 'elec005',
    title: 'Introduction to Electrodynamics',
    author: 'David J. Griffiths',
    isbn: '978-1108420419',
    status: 'issued',
    category: 'Electronics', // Could also be Physics
    publishedDate: '2017',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'electromagnetism book',
    issueDetails: {
      userId: 'user1',
      userName: 'Aisha Sharma',
      issueDate: addDays(today, -3).toISOString(),
      dueDate: addDays(today, 11).toISOString(),
    },
    description: 'A well-regarded textbook on classical electrodynamics.'
  },
  {
    id: 'elec006',
    title: 'CMOS Digital Integrated Circuits Analysis & Design',
    author: 'Sung-Mo Kang & Yusuf Leblebici',
    isbn: '978-0073380623',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2014',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'integrated circuit',
    issueDetails: {
      userId: 'user3',
      userName: 'Dr. Priya Singh',
      issueDate: addDays(today, -15).toISOString(),
      dueDate: addDays(today, -1).toISOString(), // Overdue
    },
    description: 'Focuses on the analysis and design of CMOS digital integrated circuits.'
  },
  {
    id: 'elec007',
    title: 'Signals and Systems',
    author: 'Alan V. Oppenheim & Alan S. Willsky',
    isbn: '978-0138147570',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '1996',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'signal processing',
    issueDetails: {
      userId: 'user1',
      userName: 'Aisha Sharma',
      issueDate: addDays(today, -6).toISOString(),
      dueDate: addDays(today, 8).toISOString(),
    },
    description: 'A classic textbook on signals and systems theory.'
  },
  {
    id: 'elec008',
    title: 'Power Electronics: Converters, Applications, and Design',
    author: 'Ned Mohan, Tore M. Undeland, & William P. Robbins',
    isbn: '978-0471226932',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2003',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'power supply',
    issueDetails: {
      userId: 'user2',
      userName: 'Rohan Verma',
      issueDate: addDays(today, -18).toISOString(),
      dueDate: addDays(today, -4).toISOString(), // Overdue
    },
    description: 'Comprehensive coverage of power electronics converters and their applications.'
  },
   {
    id: 'elec009',
    title: 'Embedded Systems Design with ARM Cortex-M Microcontrollers',
    author: 'Yifeng Zhu',
    isbn: '978-0982692665',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2017',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'microcontroller board',
    issueDetails: {
      userId: 'user1',
      userName: 'Aisha Sharma',
      issueDate: addDays(today, -2).toISOString(),
      dueDate: addDays(today, 12).toISOString(),
    },
    description: 'A practical guide to designing embedded systems using ARM Cortex-M microcontrollers.'
  },
  {
    id: 'elec010',
    title: 'Digital Signal Processing: Principles, Algorithms, and Applications',
    author: 'John G. Proakis & Dimitris K. Manolakis',
    isbn: '978-0131873742',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2006',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'digital signal wave',
    issueDetails: {
      userId: 'user1',
      userName: 'Aisha Sharma',
      issueDate: addDays(today, -9).toISOString(),
      dueDate: addDays(today, 5).toISOString(),
    },
    description: 'A comprehensive text on the principles and applications of digital signal processing.'
  },
  {
    id: 'elec011',
    title: 'RF Microelectronics',
    author: 'Behzad Razavi',
    isbn: '978-0132839419',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2011',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'radio frequency antenna',
    issueDetails: {
      userId: 'user2',
      userName: 'Rohan Verma',
      issueDate: addDays(today, -7).toISOString(),
      dueDate: addDays(today, 7).toISOString(),
    },
    description: 'A detailed look into the design of radio frequency integrated circuits.'
  },
  {
    id: 'elec012',
    title: 'Make: Electronics - Learning Through Discovery',
    author: 'Charles Platt',
    isbn: '978-1680456875',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2021',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'diy electronics kit',
    issueDetails: {
      userId: 'user1',
      userName: 'Aisha Sharma',
      issueDate: addDays(today, -1).toISOString(),
      dueDate: addDays(today, 13).toISOString(), // Due in 13 days
    },
    description: 'A hands-on, discovery-based approach to learning basic electronics.'
  },
  // Additional books added previously
  {
    id: 'cs001',
    title: 'Cracking the Coding Interview',
    author: 'Gayle Laakmann McDowell',
    isbn: '978-0984782867',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2015',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'interview prep book',
    description: 'A comprehensive guide for software engineering interviews.'
  },
  {
    id: 'hist001',
    title: 'Guns, Germs, and Steel',
    author: 'Jared Diamond',
    isbn: '978-0393317558',
    status: 'available',
    category: 'History',
    publishedDate: '1997',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'world history',
    description: 'Explores the factors that shaped human societies.'
  },
  {
    id: 'sf001',
    title: 'Dune',
    author: 'Frank Herbert',
    isbn: '978-0441172719',
    status: 'donated_approved',
    category: 'Fiction', // Could also be Science Fiction
    publishedDate: '1965',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'desert planet',
    donatedBy: { userId: 'user3', userName: 'Dr. Priya Singh', date: addDays(today, -50).toISOString() },
    description: 'A science fiction masterpiece set on the desert planet Arrakis.'
  },
  {
    id: 'cs002',
    title: 'The Pragmatic Programmer: Your Journey to Mastery',
    author: 'David Thomas, Andrew Hunt',
    isbn: '978-0135957059',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2019',
    coverImageUrl: "https://placehold.co/300x450.png",
    dataAiHint: "programming code",
    description: 'A guide to practical software development methodologies and best practices.'
  },
  {
    id: 'elec013',
    title: 'Foundations of Analog and Digital Electronic Circuits',
    author: 'Anant Agarwal, Jeffrey Lang',
    isbn: '978-1558607354',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2005',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'circuit diagram',
    description: 'An integrated approach to analog and digital circuits.'
  },

  // --- Start of 50+ new books in Electronics and Computer Science ---
  // Computer Science Books (Available)
  {
    id: 'cs_new_001',
    title: 'Structure and Interpretation of Computer Programs (SICP)',
    author: 'Harold Abelson, Gerald Jay Sussman',
    isbn: '978-0262510875',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '1996',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'lambda wizard',
    description: 'A classic textbook on fundamental principles of computer programming.'
  },
  {
    id: 'cs_new_002',
    title: 'Operating System Concepts',
    author: 'Abraham Silberschatz, Peter B. Galvin, Greg Gagne',
    isbn: '978-1119800361',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2021',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'gears system',
    description: 'A comprehensive guide to operating system principles.'
  },
  {
    id: 'cs_new_003',
    title: 'Computer Networking: A Top-Down Approach',
    author: 'James F. Kurose, Keith W. Ross',
    isbn: '978-0133594140',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2016',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'network cloud',
    description: 'Explores computer networking using a top-down approach.'
  },
  {
    id: 'cs_new_004',
    title: 'Database System Concepts',
    author: 'Abraham Silberschatz, Henry F. Korth, S. Sudarshan',
    isbn: '978-0078022159',
    status: 'donated_approved',
    category: 'Computer Science',
    publishedDate: '2019',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'database server',
    donatedBy: { userId: 'user2', userName: 'Rohan Verma', date: addDays(today, -15).toISOString() },
    description: 'A fundamental text on database management systems.'
  },
  {
    id: 'cs_new_005',
    title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
    author: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
    isbn: '978-0201633610',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '1994',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'abstract shapes',
    description: 'The seminal work on design patterns in software engineering.'
  },
  {
    id: 'cs_new_006',
    title: 'Compilers: Principles, Techniques, and Tools (Dragon Book)',
    author: 'Alfred V. Aho, Monica S. Lam, Ravi Sethi, Jeffrey D. Ullman',
    isbn: '978-0321486813',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2006',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'dragon code',
    description: 'The definitive textbook on compiler design.'
  },
  {
    id: 'cs_new_007',
    title: 'Code Complete: A Practical Handbook of Software Construction',
    author: 'Steve McConnell',
    isbn: '978-0735619678',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2004',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'blueprint code',
    description: 'A comprehensive guide to software construction best practices.'
  },
  {
    id: 'cs_new_008',
    title: 'The Mythical Man-Month: Essays on Software Engineering',
    author: 'Frederick P. Brooks Jr.',
    isbn: '978-0201835953',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '1995',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'people collaboration',
    description: 'Classic essays on managing complex software projects.'
  },
  {
    id: 'cs_new_009',
    title: 'Effective Java',
    author: 'Joshua Bloch',
    isbn: '978-0134685991',
    status: 'donated_approved',
    category: 'Computer Science',
    publishedDate: '2017',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'java coffee',
    donatedBy: { userId: 'user1', userName: 'Aisha Sharma', date: addDays(today, -22).toISOString() },
    description: 'Essential best practices for writing high-quality Java code.'
  },
  {
    id: 'cs_new_010',
    title: 'Python Crash Course',
    author: 'Eric Matthes',
    isbn: '978-1593279288',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2019',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'python snake',
    description: 'A fast-paced, project-based introduction to Python.'
  },
  {
    id: 'cs_new_011',
    title: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    isbn: '978-1593279509',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2018',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'javascript code',
    description: 'A modern introduction to programming with JavaScript.'
  },
  {
    id: 'cs_new_012',
    title: 'You Don\'t Know JS Yet: Get Started',
    author: 'Kyle Simpson',
    isbn: '978-1492041529',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2020',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'question mark',
    description: 'Deep dive into the core mechanisms of JavaScript.'
  },
  {
    id: 'cs_new_013',
    title: 'Learning Web Design: A Beginner\'s Guide',
    author: 'Jennifer Robbins',
    isbn: '978-1491960202',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2018',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'website wireframe',
    description: 'Covers HTML, CSS, JavaScript, and web graphics.'
  },
  {
    id: 'cs_new_014',
    title: 'Don\'t Make Me Think, Revisited: A Common Sense Approach to Web Usability',
    author: 'Steve Krug',
    isbn: '978-0321965516',
    status: 'donated_approved',
    category: 'Computer Science',
    publishedDate: '2014',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'thinking person',
    donatedBy: { userId: 'user3', userName: 'Dr. Priya Singh', date: addDays(today, -40).toISOString() },
    description: 'A classic guide to web usability principles.'
  },
  {
    id: 'cs_new_015',
    title: 'Cybersecurity for Dummies',
    author: 'Joseph Steinberg',
    isbn: '978-1119574856',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2019',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'shield lock',
    description: 'An accessible guide to understanding cybersecurity.'
  },
  {
    id: 'cs_new_016',
    title: 'The Art of Computer Programming (Volume 1-4A Boxed Set)',
    author: 'Donald E. Knuth',
    isbn: '978-0321751041',
    status: 'maintenance', // Often a reference set
    category: 'Computer Science',
    publishedDate: '2011',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'mathematical formulas',
    description: 'A monumental work on algorithms and computer programming.'
  },
  {
    id: 'cs_new_017',
    title: 'Introduction to the Theory of Computation',
    author: 'Michael Sipser',
    isbn: '978-1133187790',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2012',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'automata diagram',
    description: 'A standard textbook for theoretical computer science.'
  },
  {
    id: 'cs_new_018',
    title: 'Head First Design Patterns',
    author: 'Eric Freeman, Elisabeth Robson',
    isbn: '978-0596007126',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2004',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'brain lightbulb',
    description: 'A visually rich guide to learning design patterns.'
  },
  {
    id: 'cs_new_019',
    title: 'Refactoring: Improving the Design of Existing Code',
    author: 'Martin Fowler',
    isbn: '978-0134757599',
    status: 'issued',
    category: 'Computer Science',
    publishedDate: '2018',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'code tools',
    issueDetails: {
      userId: 'user2',
      userName: 'Rohan Verma',
      issueDate: addDays(today, -3).toISOString(),
      dueDate: addDays(today, 11).toISOString(),
    },
    description: 'Key principles and practices of code refactoring.'
  },
  {
    id: 'cs_new_020',
    title: 'Domain-Driven Design: Tackling Complexity in the Heart of Software',
    author: 'Eric Evans',
    isbn: '978-0321125217',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2003',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'domain model',
    description: 'A systematic approach to software design based on domain modeling.'
  },
  {
    id: 'cs_new_021',
    title: 'Software Architecture in Practice',
    author: 'Len Bass, Paul Clements, Rick Kazman',
    isbn: '978-0136885788',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2021',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'architecture blueprint',
    description: 'Comprehensive guide to software architecture principles and practices.'
  },
  {
    id: 'cs_new_022',
    title: 'The Linux Programming Interface',
    author: 'Michael Kerrisk',
    isbn: '978-1593272203',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2010',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'linux penguin',
    description: 'A detailed guide to Linux and UNIX system programming.'
  },
  {
    id: 'cs_new_023',
    title: 'Modern Operating Systems',
    author: 'Andrew S. Tanenbaum, Herbert Bos',
    isbn: '978-0133591620',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2014',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'computer chip',
    description: 'Explores the principles of modern operating systems.'
  },
  {
    id: 'cs_new_024',
    title: 'Data Structures and Algorithm Analysis in C++',
    author: 'Mark Allen Weiss',
    isbn: '978-0132847377',
    status: 'available',
    category: 'Computer Science',
    publishedDate: '2013',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'data structure',
    description: 'A comprehensive treatment of data structures and algorithm analysis using C++.'
  },
  {
    id: 'cs_new_025',
    title: 'Grokking Algorithms: An Illustrated Guide for Programmers',
    author: 'Aditya Y. Bhargava',
    isbn: '978-1617292231',
    status: 'donated_approved',
    category: 'Computer Science',
    publishedDate: '2016',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'algorithm illustration',
    donatedBy: { userId: 'user1', userName: 'Aisha Sharma', date: addDays(today, -10).toISOString() },
    description: 'An easy-to-follow, visual guide to algorithms.'
  },

  // Electronics Books (Available)
  {
    id: 'elec_new_001',
    title: 'Designing Audio Power Amplifiers',
    author: 'Bob Cordell',
    isbn: '978-0071640244',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2010',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'audio amplifier',
    description: 'A comprehensive guide to designing high-quality audio power amplifiers.'
  },
  {
    id: 'elec_new_002',
    title: 'Op Amps for Everyone',
    author: 'Ron Mancini',
    isbn: '978-0750677011',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2002',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'op amp circuit',
    description: 'A practical reference for operational amplifier circuits.'
  },
  {
    id: 'elec_new_003',
    title: 'Small Signal Audio Design',
    author: 'Douglas Self',
    isbn: '978-0367468892',
    status: 'donated_approved',
    category: 'Electronics',
    publishedDate: '2020',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'audio waveform',
    donatedBy: { userId: 'user2', userName: 'Rohan Verma', date: addDays(today, -25).toISOString() },
    description: 'Focuses on the design of high-quality small-signal audio circuits.'
  },
  {
    id: 'elec_new_004',
    title: 'Practical RF Circuit Design for Modern Wireless Systems, Volume I: Passive Circuits and Systems',
    author: 'Rowan Gilmore, Les Besser',
    isbn: '978-1580535212',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2003',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'rf circuit board',
    description: 'Covers passive RF circuit design for wireless systems.'
  },
  {
    id: 'elec_new_005',
    title: 'Microwave Engineering',
    author: 'David M. Pozar',
    isbn: '978-0470631553',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2011',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'microwave antenna',
    description: 'A standard textbook on microwave engineering principles.'
  },
  {
    id: 'elec_new_006',
    title: 'FPGA Prototyping by VHDL Examples: Xilinx MicroBlaze MCS SoC',
    author: 'Pong P. Chu',
    isbn: '978-1119442629',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2017',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'fpga chip',
    description: 'A hands-on guide to FPGA prototyping using VHDL.'
  },
  {
    id: 'elec_new_007',
    title: 'The TTL Data Book',
    author: 'Texas Instruments',
    isbn: 'N/A - Vintage',
    status: 'maintenance', // Reference
    category: 'Electronics',
    publishedDate: '1980s',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'datasheet book',
    description: 'Classic data book for TTL logic ICs.'
  },
  {
    id: 'elec_new_008',
    title: 'Introduction to VLSI Circuits and Systems',
    author: 'John P. Uyemura',
    isbn: '978-0471127048',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2001',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'vlsi chip design',
    description: 'Covers the design and analysis of VLSI circuits.'
  },
  {
    id: 'elec_new_009',
    title: 'Control Systems Engineering',
    author: 'Norman S. Nise',
    isbn: '978-1119468612',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2019',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'control system diagram',
    issueDetails: {
      userId: 'user3',
      userName: 'Dr. Priya Singh',
      issueDate: addDays(today, -10).toISOString(),
      dueDate: addDays(today, 4).toISOString(),
    },
    description: 'A comprehensive textbook on control systems engineering.'
  },
  {
    id: 'elec_new_010',
    title: 'Electric Machinery Fundamentals',
    author: 'Stephen J. Chapman',
    isbn: '978-0078028229',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2017',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'electric motor',
    description: 'Covers the fundamentals of electric machinery and transformers.'
  },
  {
    id: 'elec_new_011',
    title: 'Semiconductor Physics and Devices',
    author: 'Donald A. Neamen',
    isbn: '978-0073529585',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2011',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'semiconductor wafer',
    description: 'A detailed treatment of semiconductor device physics.'
  },
  {
    id: 'elec_new_012',
    title: 'Digital Integrated Circuits: A Design Perspective',
    author: 'Jan M. Rabaey, Anantha Chandrakasan, Borivoje Nikolic',
    isbn: '978-0130909961',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2003',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'integrated circuit layout',
    description: 'Focuses on the design of digital integrated circuits from a modern perspective.'
  },
  {
    id: 'elec_new_013',
    title: 'Analog Filter Design',
    author: 'M. E. Van Valkenburg',
    isbn: '978-0195107340',
    status: 'available',
    category: 'Electronics',
    publishedDate: '1995', // Classic text
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'filter response graph',
    description: 'A classic textbook on analog filter design techniques.'
  },
  {
    id: 'elec_new_014',
    title: 'Antenna Theory: Analysis and Design',
    author: 'Constantine A. Balanis',
    isbn: '978-1118642061',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2016',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'antenna radiation pattern',
    description: 'Comprehensive coverage of antenna theory and design.'
  },
  {
    id: 'elec_new_015',
    title: 'Communication Systems',
    author: 'Simon Haykin, Michael Moher',
    isbn: '978-0470460821',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2009',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'communication satellite',
    description: 'Covers analog and digital communication systems.'
  },
  {
    id: 'elec_new_016',
    title: 'Robotics: Modelling, Planning and Control',
    author: 'Bruno Siciliano, Lorenzo Sciavicco, Luigi Villani, Giuseppe Oriolo',
    isbn: '978-1846286421',
    status: 'available',
    category: 'Electronics', // Also Mechatronics/CS
    publishedDate: '2009',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'robotic arm',
    description: 'A comprehensive text on robotics, covering modeling, planning, and control.'
  },
  {
    id: 'elec_new_017',
    title: 'Linear Systems and Signals',
    author: 'B. P. Lathi, Roger Green',
    isbn: '978-0190200176',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2017',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'signal graph',
    description: 'Covers continuous and discrete-time linear systems and signals.'
  },
  {
    id: 'elec_new_018',
    title: 'Electromagnetic Compatibility Engineering',
    author: 'Henry W. Ott',
    isbn: '978-0470189306',
    status: 'donated_approved',
    category: 'Electronics',
    publishedDate: '2009',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'emc testing chamber',
    donatedBy: { userId: 'user3', userName: 'Dr. Priya Singh', date: addDays(today, -33).toISOString() },
    description: 'A practical guide to EMC engineering principles and practices.'
  },
  {
    id: 'elec_new_019',
    title: 'Analog Integrated Circuit Design',
    author: 'Tony Chan Carusone, David A. Johns, Kenneth W. Martin',
    isbn: '978-0470770108',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2011',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'analog circuit chip',
    description: 'Covers the analysis and design of analog integrated circuits.'
  },
  {
    id: 'elec_new_020',
    title: 'Measurement and Instrumentation: Theory and Application',
    author: 'Alan S. Morris, Reza Langari',
    isbn: '978-0128008843',
    status: 'issued',
    category: 'Electronics',
    publishedDate: '2015',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'oscilloscope display',
    issueDetails: {
      userId: 'user1',
      userName: 'Aisha Sharma',
      issueDate: addDays(today, -5).toISOString(),
      dueDate: addDays(today, 9).toISOString(),
    },
    description: 'Provides a comprehensive foundation in measurement and instrumentation.'
  },
   {
    id: 'elec_new_021',
    title: 'Electric Drives',
    author: 'Ion Boldea, S.A. Nasar',
    isbn: '978-1498729792',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2016',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'industrial motor drive',
    description: 'Covers the theory and application of electric drives.'
  },
  {
    id: 'elec_new_022',
    title: 'Digital Control of Dynamic Systems',
    author: 'Gene F. Franklin, J. David Powell, Michael Workman',
    isbn: '978-0130825839',
    status: 'available',
    category: 'Electronics',
    publishedDate: '1997',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'digital control loop',
    description: 'A classic text on digital control system design.'
  },
  {
    id: 'elec_new_023',
    title: 'High-Speed Digital Design: A Handbook of Black Magic',
    author: 'Howard Johnson, Martin Graham',
    isbn: '978-0133957242',
    status: 'available',
    category: 'Electronics',
    publishedDate: '1993',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'signal integrity waveform',
    description: 'Addresses signal integrity issues in high-speed digital design.'
  },
  {
    id: 'elec_new_024',
    title: 'Solid State Electronic Devices',
    author: 'Ben G. Streetman, Sanjay Kumar Banerjee',
    isbn: '978-0133356038',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2014',
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'transistor diagram',
    description: 'A fundamental text on solid state electronic devices.'
  },
  {
    id: 'elec_new_025',
    title: 'Fundamentals of Power Electronics',
    author: 'Robert W. Erickson, Dragan Maksimovic',
    isbn: '978-0387729818',
    status: 'available',
    category: 'Electronics',
    publishedDate: '2001', // Older edition, but still highly regarded
    coverImageUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'power converter schematic',
    description: 'A comprehensive textbook on power electronics.'
  }
  // --- End of 50+ new books ---
];

export const mockTransactions: Transaction[] = [
  {
    id: 'txn1',
    bookId: 'book1',
    bookTitle: 'The Digital Fortress',
    userId: 'user1',
    userName: 'Aisha Sharma',
    type: 'issue',
    timestamp: addDays(today, -10).toISOString(),
    dueDate: addDays(today, 4).toISOString(),
  },
  {
    id: 'txn2',
    bookId: 'book4',
    bookTitle: 'Clean Code',
    userId: 'user2',
    userName: 'Rohan Verma',
    type: 'donate_request',
    timestamp: addDays(today, -2).toISOString(),
  },
  {
    id: 'txn3',
    bookId: 'book5',
    bookTitle: 'The Laws of Thermodynamics',
    userId: 'user3',
    userName: 'Dr. Priya Singh',
    type: 'issue',
    timestamp: addDays(today, -20).toISOString(),
    dueDate: addDays(today, -5).toISOString(),
  },
   {
    id: 'txn4',
    bookId: 'book6',
    bookTitle: 'Introduction to Algorithms',
    userId: 'user1',
    userName: 'Aisha Sharma',
    type: 'donate_approve',
    timestamp: addDays(today, -28).toISOString(),
  }
  // Mock transactions for new electronics books could be added here if needed
  // For example, for 'elec001' issued to user1:
  // {
  //   id: 'txnElec001',
  //   bookId: 'elec001',
  //   bookTitle: 'Grob\'s Basic Electronics',
  //   userId: 'user1',
  //   userName: 'Aisha Sharma',
  //   type: 'issue',
  //   timestamp: addDays(today, -12).toISOString(),
  //   dueDate: addDays(today, 2).toISOString(),
  // }
];
